ASEGeoOpt:
    data_id: 0
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.1
ASEMD:
    data_id: -1
    dump_rate: 1
    init_temperature: null
    init_velocity: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 5000
ASEMD_1:
    data_id: -1
    dump_rate: 1
    init_temperature: null
    init_velocity: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 100
ASEMD_1_thermostat:
    friction: 0.01
    temperature: 300
    time_step: 0.5
ASEMD_thermostat:
    friction: 0.01
    temperature: 300
    time_step: 0.5
ConfigurationSelection:
    n_configurations: 250
    seed: 1234
ConfigurationSelection_1:
    n_configurations: 20
    seed: 1234
MLModel:
    distance_nb:
        _type: distanceNb_dataclass
        value:
            add_species: true
            covariance_type: ard_se
            cutoff: 6.0
            delta: 0.1
            n_sparse: 50
            order: 2
            sparse_method: CUR_POINTS
            theta_uniform: 1.0
    gap:
        _type: GapParameter_dataclass
        value:
            default_sigma: '{0.0001 0.01 0.01 0.01}'
            e0_method: average
            sparse_jitter: 1.0e-10
    soap:
        _type: soap_dataclass
        value:
            add_species: true
            covariance_type: dot_product
            cutoff: 3
            cutoff_transition_width: 0.5
            delta: 1.0
            l_max: 5
            n_max: 5
            n_sparse: 50
            sigma: 0.5
            sparse_method: CUR_POINTS
            zeta: 4.0
    use_energy: true
    use_forces: true
    use_stresses: false
Packmol:
    box: null
    count:
    - 10
    density: 997
    tolerance: 2.0
SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: O
